application: metaworld
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- appstats: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.py
