application: itwmetaworld
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- appstats: on

libraries:
- name: jinja2
  version: latest

handlers:
#For D.O.H
- url: /static/js/dtk/util/doh/runner\.html
  static_files: static/js/dtk/util/doh/runner.html
  upload: static/js/dtk/util/doh/runner\.html
- url: /static
  static_dir: static
- url: .*
  script: main.py
